id: IB1016D1B
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T00:34:48.932898'
last_modified: '2022-06-19T00:34:48.932912'
parser: null
source_metadata:
  title: A mes zhabss (1597–1659) Record of Teachings Received, parts I-XI
  author: ཨ་མྱེས་ཞབས་ངག་དབང་ཀུན་དགའ་བསོད་ནམས།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2015-07-05);
    Tibetan pagination; unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Guru Lama, Sachen International, Kathmandu (Nepal) (si)
  - Editorial process:Mathias Fermer (mf), བསམ་གྲུབ། (Dharamsala) (sdr)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:བསམ་གྲུབ། (sdr)
  text_witnesses: https://sakyaresearch.org/sources/602
  bases:
    bc0e:
      title: A mes zhabss (1597–1659) Record of Teachings Received, parts I-XI
      order: 1
      base_file: bc0e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
